### ISSUE TITLE
where's my name

### ISSUE THREAD

**Issue by AdamKadmon** [kuplion/Exile-Parachute-and-Halo#1]
I WILL FILE A DMCA, YOU HAVE 60 HOURS TO COMPLY!!! REEEEEEEEEEEEEEEEEE

**Comment by kuplion** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by AdamKadmon** [comment]
![ybygyat](https://user-images.githubusercontent.com/21025798/38222479-f1f93ef8-36b2-11e8-9404-25ecbbbfb1b3.png)
